export const constants = {
    // BMI, HEALTHY WEIGHT LOSS, HEALTHY WEIGHT GAIN, ALCOHOL CONSUMPTION LIMIT, CIGARETTE CONSUMPTION LIMIT
    BMI : {
        NORMAL_LOWER_LIMIT : 18.5,
        OVERWEIGHT_LOWER_LIMIT : 25,
        OBESE_LOWER_LIMIT : 30
    },
    ALCOHOL: {
        WEEKLY_UNIT_MAX_LIMIT : 14
    },
    CIGARETTES: {
        UNHEALTHY_LOWER_LIMIT : 1
    }
};
